stages:
  - update_github

update_github:
  stage: update_github
  script:
    - git config --global user.email "sarwan.sharma@hotmail.com"
    - git config --global user.name "Sarwan Sharma"
    - echo -e "protocol=https\nhost=github.com\nusername=$GITHUB_USERNAME\npassword=$GITHUB_ACCESS_TOKEN" | git credential approve
    - git clone https://github.com/sarwansharma/velocitysynctesthpe.git
    - cd velocitysynctesthpe
    - git remote add github https://github.com/sarwansharma/velocitysynctesthpe.git
    - git pull github main
    - git push github main
  only:
    - main  # Adjust this to match your main branch name
