stages:
  - update_github

update_github:
  stage: update_github
  script:
    - git config --global user.email "sarwan.sharma@hotmail.com"
    - git config --global user.name "Sarwan Sharma"
    - git clone https://gitlab.example.com/root/velocitysynctesthpe.git
    - cd velocitysynctesthpe
    - git remote add github https://github.com/sarwansharma/velocitysynctesthpe.git
    - git pull github main
    - git push github HEAD:main
  only:
    - main  # Adjust this to match your main branch name
